### ISSUE TITLE
Starting multiple instances of a gretty task / running many single instances of gretty tasks

### ISSUE THREAD

**Issue by daves125125** [akhikhl/gretty#112] opened 2014-11-03 22:55 UTC
Hi,

More of a question than an issue, but I wasn't sure if the following workflow was supported.

Suppose I want to deploy multiple independent instances of jetty, each running a single independent application on a single host but using a different port, how would i go about this? 

I currently have AppA and AppB. Both separate applications and they have independent release cycles. For the moment i can easily deploy AppA from a CI server using something along the lines of:

./gradlew jettyStartWar -DAppASpecficVariables > someLogFile.log &

If I run the same command, on the same host for AppB (with separate configuration, different port, context etc) I get the following error:

* What went wrong:
Execution failed for task ':jettyStartWar'.
> Web-server is already running.

I've read about the farm tasks and their various functions but I don't want deploy these two applications as a single release or even associate them together in a servlet container.

Any advice or help would be much appreciated.

Thanks,
Dave.

**Comment by mahengyang** [comment] 2015-01-15 13:10
I think multiple instances jetty/tomcat will be needed by most developer

**Comment by akhikhl** [comment] 2015-01-25 22:29
does setting port triplet:
```
gretty {
  httpPort = 8080
  servicePort = 9090
  statusPort = 9091
}
```
for each servlet container solves the problem?

**Comment by aruka-pragmatists** [comment] 2015-01-26 16:11
I'm not the OP, but I just ran into this issue 5 minutes ago, and can confirm that setting a unique port triplet of httpPort, servicePort and statusPort solves the problem and allows you to have multiple containers managed by Gretty running at the same time.

**Comment by mahengyang** [comment] 2015-02-05 04:46
yes this works for me

**Comment by akhikhl** [comment] 2015-03-01 19:29
I close the issue since choosing a unique combination of httpPort/httpsPort, servicePort and statusPort solves the issue.

**Closed** 2015-03-01 19:30 UTC
Labels: waiting for feedback

**Comment by yassenb** [comment] 2015-07-28 09:34
The described solution does not work in my case.

**Comment by bgreen1005** [comment] 2016-10-24 08:18
I'm also interested in this functionality. It doesn't seem possible to have two different gretty servlet containers running at the same time from a single gradle task.

**Comment by sriniadhiwork** [comment] 2017-01-27 13:02
I have been struggling with this for the past two days.

* What went wrong:
Execution failed for task ':project-name:tomcatStartWar'.
> java.util.concurrent.ExecutionException: java.net.BindException: Address already in use: JVM_Bind

I tried all combinations

gretty {
    port = 18081
      servicePort = 9090
     statusPort = 9091

I have killed all the java processes before start, no avail. After this fails, it does leave two java processes listening to ports (I believe 55573 or so).  

It will be nice if there is a way to know which port is already in use.

**Comment by rosw12** [comment] 2018-06-05 18:06
I can confirm that this still works with version 2.2.0 of the actively maintianed fork https://github.com/gretty-gradle-plugin/gretty/, although you will also need to use a new portPropertiesFile:

``` groovy
gretty {
  httpPort = 8081
  servicePort = 9092
  statusPort = 9093
  portPropertiesFile = "gretty_port_2.properties"
}
```
